### ISSUE TITLE
EthernetClient::read(buf, size) returns "opposite sense" for EOF

### ISSUE THREAD

**Issue by ssilverman** [vjmuzik/NativeEthernet#13]
It's been my experience that a return of -1 means EOF and a return of 0 means "nothing available". Why does this function return the opposite? I know this may just be a convention thing, it just seems odd to me here.

**Comment by vjmuzik** [comment]
That’s the behavior from the normal Ethernet Library so it carried over to here.  This comes from the socketRecv function, but you’re right though I don’t know why they chose for -1 to be no data and for 0 to be socket closed.

**Comment by ssilverman** [comment]
Yeah, I saw it was from socketRecv, I was hoping it could change... :)
